# This is a config for E2B sandbox template.
# You can use template ID (qqxxsc3tfxjvfwa7fn5n) or template name (v0-nextjs-build-new) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("v0-nextjs-build-new") # Sync sandbox
# sandbox = await AsyncSandbox.create("v0-nextjs-build-new") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('v0-nextjs-build-new')

team_id = "72de489b-53a9-45de-b85f-2d8240d17639"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "v0-nextjs-build-new"
template_id = "qqxxsc3tfxjvfwa7fn5n"
